urls.py
"""
Definition of urls for WCI_GarmentInventory.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('app.urls'), name="home"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

app/forms.py
"""
Definition of forms.
"""
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import *
import json
from datetime import date
from django.forms.widgets import *
from django.utils.translation import ugettext_lazy as _

# Login Form
class BootstrapAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=200,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

# Customer Support Form
IssueOptions=[
    ('rehomed', 'Conveyor needs to be Rehomed'),
    ('power', 'Power outage'),
    ('slots', 'Slot numbers are off'),
    ('info', 'Employee or Garment information cannot be found'),
    ('sql', 'Database is not updating'),
    ('keypad', 'Keypad is not working'),
    ('other', 'If reason is not listed, please explain below')
]

class CustomerServiceForm(forms.Form):
    name = forms.CharField(max_length=40)
    email = forms.EmailField()
    to = forms.EmailField()
    issue = forms.ChoiceField(choices=IssueOptions)
    comments = forms.CharField(required=False, widget=forms.Textarea)



##### INVENTORY TAB INFORMATION ######

# Garment Info Form
class GarmSortForm(forms.ModelForm):  
    # Can search by JOB to filter specific Garments related to Job
    dgarms = {}
    list_garmdef= []
    for garm in Garmdefaultvalues.objects.all():
        if garm.jobid.job in dgarms:
            dgarms[garm.jobid.job].append(garm.garmentdefaultdef)
        else:
            dgarms[garm.jobid.job] = [garm.garmentdefaultdef]
        list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    jobs = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    jobs_select = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobs]))
    garmdef_select = forms.ChoiceField(choices=(list_garmdef))

    jobs = json.dumps(jobs)
    garms = json.dumps(dgarms)

    #EmployeeID filters specific Employee Name 

    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice, required=False)
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    slotnumber = forms.IntegerField(required=False)
    pickupdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local'}), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dropoffdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local', }), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)


    class Meta:
        model = Garmentinvactivity
        fields = [ "jobs_select", "garmdef_select", "garmentnumber",
                 "slotnumber", "rfid_barcode", "conveyornumber", 
                 "garmlocation", "loaned", "missing", 
                 "altid", "employeeid", "jobid", "garmentdefaultid", "divdeptid",
                 "pickupdate", "dropoffdate", "dateadded", "alterations"]


# Inventory Search
class InvSearchForm(forms.ModelForm):
    class Meta:
        model = Inventorysearch
        fields = ["garmentnumber", "rfid", "job",
                  "description", "employeeid", "garmentdefaultid", ]
#"employeename",

# Inv Stats per Garment Number
class GarmInvStatsForm(forms.ModelForm):
    class Meta:
        model = Garminvstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentdefaultid", "jobid",
                    "job", "garmentnumber", ]

class GarmActForm(forms.ModelForm):
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice)
    assigned = forms.ChoiceField(choices=Garmentinvactivity.assignedChoice)

    class Meta:
        model = Garmentinvactivity
        fields = '__all__'




###### EMPLOYEE TAB INFORMATION ######

# Employee Information Tab
class EmpInfoForm(forms.ModelForm):
    #djobs = {}
    #list_jobs = []
    #for jd in Jobdefinitions.objects.all():
    #    if jd.divdeptid.combineddef in djobs:
    #        djobs[jd.divdeptid.combineddef].append(jd.job)
    #    else:
    #        djobs[jd.divdeptid.combineddef] = [jd.job]
    #    list_jobs.append((jd.job, jd.job))

    #divs = [str(divdept_name) for divdept_name in Divdept.objects.all()]

    #divdept_select = forms.ChoiceField(choices=([(divdept_name, divdept_name) for divdept_name in divs]))
    #jobdef_select = forms.ChoiceField(choices=(list_jobs))
    
    #divs = json.dumps(divs)
    #jobs = json.dumps(djobs)

    gender = forms.ChoiceField(choices=Employeecreate.genderChoices, required=False)
    garmsize = forms.ChoiceField(choices=Employeecreate.garmSizeChoices, required=False)
    hiredate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Employeecreate
        fields = [ "employeeid", "empfirstname", "emplastname", 
                  "gender", "shirtsize", "pantsize", "shoesize", "garmlength", 
                  "hiredate", "alterationinstructions", "empmiddleinitial",
                  "empemail", "slotassignment", "conveyor", "jacketsize", "jobid", "divdeptid"]
#"divdept_select", "jobdef_select",
# Assigned Garments (To Specific Employee) Form 
class AssignedGarmsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentinventory
        fields = ["employeeid", "garmentid", "rfid", "garmenttype", 
                  "slotnumber", "lastpickedup", "lastdroppedoff", "missing",
                  "empgarmpar", "garmentdefaultid",]

# Garments Assigned to Specific Job Form
class JobGarmsForm(forms.ModelForm):
    class Meta:
        model = Joboutfits
        fields = ["employeeid", "job", "garmenttype", 
                  "garmdescription", "garmsize", "multiuse", "totalperjob",
                  "reservestock", "garmentdefaultid", "jobid", ]

# Employee Stats Regarding Garms Assigned to Employye
class EmpGarmStatsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentorderstats
        fields = ["employeeid", "garmenttype", "empgarmpar", "totaljobpar", 
                  "totalreservestock", "maxorder", ]







###### Garment Orders Tab ########

#Order Landing Table
class SearchOrders(forms.ModelForm):
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Searchgarmorders
        fields = ["garmentorderid", "employeeid", "garmentdefaultid",  "garmenttype", "garmdescription",
                  "amount", "reason", "orderplaceddate", "orderplacedby", "orderstatus",  ]#"job",



# Garment Orders Search Form 
class GarmentOrdersForm(forms.ModelForm):
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'missing'}), initial=date.today)
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'placedon'}), initial=date.today)
    reason = forms.CharField(widget=TextInput(attrs={'class':'reason'}))
    orderstatus = forms.ChoiceField(choices=Garmentorders.statusChoices)
    loaned = forms.ChoiceField(choices=Garmentorders.loanedChoices)
    amount = forms.CharField(widget=forms.TextInput(attrs={'class':'amt'}))
    orderplacedby = forms.CharField(widget=forms.TextInput(attrs={'class':'placedby'}))

    class Meta:
        model = Garmentorders
        fields =  ["employeeid", "reason", "amount",
                  "orderplaceddate", "orderplacedby", "orderstatus", 
                  "missing", "loaned",]



class GarmentOrderIDStats(forms.ModelForm):
    class Meta:
        model = Garmorderidstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentorderid"]



    #ogarms = {}
    #list_garmdef= []
    #for garm in Garmdefaultvalues.objects.all():
    #    if garm.jobid.job in ogarms:
    #        ogarms[garm.jobid.job].append(garm.garmentdefaultdef)
    #    else:
    #        ogarms[garm.jobid.job] = [garm.garmentdefaultdef]
    #    list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    #jobchoices = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    #select_job = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobchoices]))
    #select_garmdef = forms.ChoiceField(choices=(list_garmdef))

    #jobchoices = json.dumps(jobchoices)
    #garmchoices = json.dumps(ogarms)

app/templates/app/garmentorders/GarmOrderDetails.html
{% extends "app/garmentorders/GarmentOrdersLayout.html" %}

{% block ordercontent %}


<head>
	<link rel="stylesheet" type="text/css" href="../static/app/content/GarmOrderDetails.css">
</head>

    <div class="Title">
            <h2>Order Details</h2> 
    </div>

        <div class="blank"></div>
		
		<div class="Stats">
                <div class="OrdersTable">
                	{% for ord in orderstats %}
                    
                    <p>Inventory Info for Order ID: <b>{{ ord.garmentorderid }}</b></p>
                    <div class="Orders">
                        <table class="table table-bordered" id="ordertable">
                            <tbody>
								<tr>
									<th>Garment Type</th>
									<td>{{ ord.garmenttype }}</td>
								</tr>
								<tr>
									<th>Max Per Job</th>
									<td>{{ ord.totalperjob }}</td>
								</tr>
								<tr>
									<th>Reserve Stock</th>
									<td>{{ ord.totalreservestock }}</td>
								</tr>
								<tr>
									<th>Max Inv</th>
									<td>{{ ord.maxamountinv }}</td>
								</tr>
								<tr>
									<th>Total In Inv</th>
									<td>{{ ord.totalinv }}</td>
								</tr>
								<tr>
									<th>Total Assigned</th>
									<td>{{ ord.totalassigned }}</td>
								</tr>
								<tr>
									<th>Total Unassigned</th>
									<td>{{ ord.totalunassigned }}</td>
								</tr>
								<tr>
									<th>Inv % Full</th>
									<td>{{ ord.percentfull }}%</td>
								</tr>
                        </tbody>
                    </table>
                </div>
                {% endfor %}
            </div>
		</div>
	

		<div class="Order">

			<p id="title">Order Form:</p>
		
			<form class="GarmentOrdersForm" id="garmOrders" method="POST">
				{% csrf_token %}
				<div class="FirstRow">
					<p id="garmentorderid">
						<label for="id_garmentorderid">Order ID</label>
						{{orderdetailform.garmentorderid}}
					</p>
				</div>

				<div class="SecondRow">
                    <p class="SelectJob">
                        <label for="id_select_job">Job: </label>
                             <br>
                        {{orderdetailform.select_job}}
                    </p>
                    <p class="SelectGarment">
                        <label for="id_select_garmdef">Garment Type: </label>
                            <br>
                        {{orderdetailform.select_garmdef}}
                    </p>
                </div>

                <div class="ThirdRow">
                	<p id="reason">
                		<label for="id_reason">Reason/Purpose</label>
                			<br>
                		{{orderdetailform.reason}}
                	</p>
                	<p id="amount">
                		<label for="id_amount">Amount</label>
                			<br>
                		{{orderdetailform.amount}}
                	</p>
                	<p id="status">
                		<label for="id_orderstatus">Status</label>
                			<br>
                		{{orderdetailform.orderstatus}}
                	</p>
                </div>

                <div class="FourthRow">
                	<p id="orderby">
                		<label for="id_orderplacedby">Order Placed By</label>
                			<br>
                		{{orderdetailform.orderplacedby}}
                	</p>
                	<p id="orderdate">
                		<label for="id_orderplaceddate">Order Placed On</label>
                			<br>
                		{{orderdetailform.orderplaceddate}}
                	</p>
                </div>

                <p id="submit">
                    <input type="submit" id="edit" value="Edit Order">
                </p>
			</form>
		</div>


{% endblock %}

	{% block actionbuttons %}
        <a href="{% url 'CreateGarmentOrder' %}" class="Add">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add</button>
        </a>


{% endblock %}

app/templates/app/garmentorders/GarmentOrdersLanding.html
{% extends "app/garmentorders/GarmentOrdersLayout.html" %}

{% block ordercontent %}
<head>
    <link rel="stylesheet" type="text/css" href="../static/app/content/GarmentOrderLanding.css">
</head>

    <div class="Title">
            <h2>Search All Garment Orders</h2> 
    </div>

        <div class="blank"></div>

        <form class="GarmSearchBox" method="GET">

            <div class="OrderID_Search">
                <h2>Order ID</h2>
                {{ordfilter.form.garmentorderid}}
            </div> 

            <div class="EmpID_Search">
                <h2>Employee ID</h2>
                {{ordfilter.form.employeeid}}
            </div>

            <div class="Job_Search">
                <h2>Job</h2>
                {{ordfilter.form.job}}
            </div>

            <div class="Status_Search">
                <h2>Order Status</h2>
                {{ordfilter.form.orderstatus}}
            </div>
                
            <div class="GarmSearchButtons">
                <button id="search" onlick="" class="SearchOrder">Search</button>
                <a href="{% url 'GarmentOrdersLanding' %}" class="OrderSearch" id="orderButton">
                    <p id="resetemp">Reset</p>
                </a>
            </div>

        </form>

        <div class="GarmOrderInfo">
                <div class="GarmOrdersTable">
                    <table class="table table-bordered" id="garmorderstable">
                        <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Emp ID</th>
                                <th>Job</th>
                                <th>Type</th>
                                <th>Amount</th>
                                <th>Reason</th>
                                <th>Ordered By</th>
                                <th>Ordered On</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ord in ordfilter.qs %}
                                <tr>
                                    <td><a href="/OrderDetails/{{ord.garmentorderid}}">{{ ord.garmentorderid }}</td>
                                    <td><a href="/EmployeeDetails/{{ord.employeeid}}">{{ ord.employeeid }}</a></td>
                                    <td></td>
                                    <td>{{ ord.garmenttype }}</td>
                                    <td>{{ ord.amount }}</td>
                                    <td>{{ ord.reason }}</td>
                                    <td>{{ ord.orderplacedby }}</td>
                                    <td>{{ ord.orderplaceddate }}</td>
                                    <td>{{ ord.orderstatus }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

    {% endblock %}
    
    {% block actionbuttons %}
        <a href="{% url 'CreateGarmentOrder' %}" class="Add">
            <button class="AddButton" id="addButton" onclick="SelectAction()">New<br>Order</button>
        </a>

  {% endblock %}

app/templates/app/garmentorders/GarmentOrdersLayout.html
{% extends "app/layout.html" %}
{% block maincontent %}
<head>
    <link rel="stylesheet" type="text/css" href="../static/app/content/GarmentOrdersLayout.css">
</head>
    
    <div class="SearchBar">
        {% block search %}
        {% endblock %}
    </div>

    <div class="GarmOrdersResults">

        {% block ordercontent %}
        {% endblock %}

    </div>
    
    <div class="ActionButtons">

        {% block actionbuttons %}
        {% endblock %}

    </div>

{% endblock %}

app/templates/app/garmentorders/NewOrder.html
{% extends "app/garmentorders/GarmentOrdersLayout.html" %}

{% block ordercontent %}


<head>
	<link rel="stylesheet" type="text/css" href="../static/app/content/NewOrder.css">
</head>

    <div class="Title">
            <h2>Add New Order</h2> 
    </div>

        <div class="blank"></div>

		<div class="Order">

			<p id="title">Order Form:</p>
		
			<form class="GarmentOrdersForm" id="garmOrders" method="POST" action="{% url 'GarmentOrdersLanding' %}">
                {% csrf_token %}
                {{ form }}
 				<div class="FirstRow">
					<p id="garmentorderid">
						<label for="id_garmentorderid">Order ID</label>
						{{order.garmentorderid}}
					</p>
				</div>

               <div class="SecondRow">
                    <p class="SelectJob">
                        <label for="id_select_job">Job: </label>
                             <br>
                        {{order.select_job}}
                    </p>
                    <p class="SelectGarment">
                        <label for="id_select_garmdef">Garment Type: </label>
                            <br>
                        {{order.select_garmdef}}
                    </p>
                </div>
<!--
                <div class="ThirdRow">
                	<p id="reason">
                		<label for="id_reason">Reason/Purpose</label>
                			<br>
                		{{order.reason}}
                	</p>
                	<p id="amount">
                		<label for="id_amount">Amount</label>
                			<br>
                		{{order.amount}}
                	</p>
                </div>

                <div class="FourthRow">
                	<p id="orderby">
                		<label for="id_orderplacedby">Order Placed By</label>
                			<br>
                		{{order.orderplacedby}}
                	</p>
                	<p id="orderdate">
                		<label for="id_orderplaceddate">Order Placed On</label>
                			<br>
                		{{order.orderplaceddate}}
                	</p>
                </div>
-->
                <p id="submit">
                    <input type="submit" id="newOrder" value="Submit Order">
                </p>
			</form>
		</div>


	{% endblock %}

	{% block actionbuttons %}
        <a href="{% url 'CreateGarmentOrder' %}" class="Add">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add</button>
        </a>

    <script language="javascript">
        $('#id_select_job').change(function() {populateGarmDef(this)});
        
        jobchoices = {{ order.jobchoices | safe }};
        garmchoices = {{ order.garmchoices | safe }};
        populateJob();
        $("#id_select_garmdef").empty();
        $("#id_select_garmdef").append('<option value="" disabled selected>Select Job First</option>');
        function populateJob() {
            $('#id_select_job').empty();
            $("#id_select_job").append('<option value="" disabled selected>Select Job</option>');
            $.each(jobchoices, function(v) {
                $('#id_select_job')
                    .append($("<option></option>")
                    .attr("value", jobchoices[v])
                    .text(jobchoices[v]));
            });
        }

        function populateGarmDef(event) {
            jobchoice = $("#id_select_job option:selected").text();
            $("#id_select_garmdef").empty();
            $("#id_select_garmdef").append('<option value="" disabled selected>Select Garment Type</option>');
            for (let [b, bchoices] of Object.entries(garmchoices)) {
                if (b == jobchoice) {                    
                    for (garmchoice in bchoices) {
                        $('#id_select_garmdef')
                            .append($("<option></option>")
                                .attr("value", bchoices[garmchoice])
                                .text(bchoices[garmchoice]));
                    }
                }
            }
        }
    </script>

{% endblock %}