urls.py
"""
Definition of urls for WCI_GarmentInventory.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('app.urls'), name="home"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

app/forms.py
"""
Definition of forms.
"""
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import *
import json
from datetime import date
from django.forms.widgets import *
from django.utils.translation import ugettext_lazy as _

# Login Form
class BootstrapAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=200,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

# Customer Support Form
IssueOptions=[
    ('rehomed', 'Conveyor needs to be Rehomed'),
    ('power', 'Power outage'),
    ('slots', 'Slot numbers are off'),
    ('info', 'Employee or Garment information cannot be found'),
    ('sql', 'Database is not updating'),
    ('keypad', 'Keypad is not working'),
    ('other', 'If reason is not listed, please explain below')
]

class CustomerServiceForm(forms.Form):
    name = forms.CharField(max_length=40)
    email = forms.EmailField()
    to = forms.EmailField()
    issue = forms.ChoiceField(choices=IssueOptions)
    comments = forms.CharField(required=False, widget=forms.Textarea)



##### INVENTORY TAB INFORMATION ######

# Garment Info Form
class GarmSortForm(forms.ModelForm):  
    # Can search by JOB to filter specific Garments related to Job
    dgarms = {}
    list_garmdef= []
    for garm in Garmdefaultvalues.objects.all():
        if garm.jobid.job in dgarms:
            dgarms[garm.jobid.job].append(garm.garmentdefaultdef)
        else:
            dgarms[garm.jobid.job] = [garm.garmentdefaultdef]
        list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    jobs = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    jobs_select = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobs]))
    garmdef_select = forms.ChoiceField(choices=(list_garmdef))

    jobs = json.dumps(jobs)
    garms = json.dumps(dgarms)

    #EmployeeID filters specific Employee Name 

    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice, required=False)
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    slotnumber = forms.IntegerField(required=False)
    pickupdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local'}), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dropoffdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local', }), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)


    class Meta:
        model = Garmentinvactivity
        fields = [ "jobs_select", "garmdef_select", "garmentnumber",
                 "slotnumber", "rfid_barcode", "conveyornumber", 
                 "garmlocation", "loaned", "missing", 
                 "altid", "employeeid", "jobid", "garmentdefaultid", "divdeptid",
                 "pickupdate", "dropoffdate", "dateadded", "alterations"]


# Inventory Search
class InvSearchForm(forms.ModelForm):
    class Meta:
        model = Inventorysearch
        fields = ["garmentnumber", "rfid", "job",
                  "description", "employeeid", "garmentdefaultid", ]
#"employeename",

# Inv Stats per Garment Number
class GarmInvStatsForm(forms.ModelForm):
    class Meta:
        model = Garminvstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentdefaultid", "jobid",
                    "job", "garmentnumber", ]

class GarmActForm(forms.ModelForm):
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice)
    assigned = forms.ChoiceField(choices=Garmentinvactivity.assignedChoice)

    class Meta:
        model = Garmentinvactivity
        fields = '__all__'




###### EMPLOYEE TAB INFORMATION ######

# Employee Information Tab
class EmpInfoForm(forms.ModelForm):
    #djobs = {}
    #list_jobs = []
    #for jd in Jobdefinitions.objects.all():
    #    if jd.divdeptid.combineddef in djobs:
    #        djobs[jd.divdeptid.combineddef].append(jd.job)
    #    else:
    #        djobs[jd.divdeptid.combineddef] = [jd.job]
    #    list_jobs.append((jd.job, jd.job))

    #divs = [str(divdept_name) for divdept_name in Divdept.objects.all()]

    #divdept_select = forms.ChoiceField(choices=([(divdept_name, divdept_name) for divdept_name in divs]))
    #jobdef_select = forms.ChoiceField(choices=(list_jobs))
    
    #divs = json.dumps(divs)
    #jobs = json.dumps(djobs)

    gender = forms.ChoiceField(choices=Employeecreate.genderChoices, required=False)
    garmsize = forms.ChoiceField(choices=Employeecreate.garmSizeChoices, required=False)
    hiredate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Employeecreate
        fields = [ "employeeid", "empfirstname", "emplastname", 
                  "gender", "shirtsize", "pantsize", "shoesize", "garmlength", 
                  "hiredate", "alterationinstructions", "empmiddleinitial",
                  "empemail", "slotassignment", "conveyor", "jacketsize", "jobid", "divdeptid"]
#"divdept_select", "jobdef_select",
# Assigned Garments (To Specific Employee) Form 
class AssignedGarmsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentinventory
        fields = ["employeeid", "garmentid", "rfid", "garmenttype", 
                  "slotnumber", "lastpickedup", "lastdroppedoff", "missing",
                  "empgarmpar", "garmentdefaultid",]

# Garments Assigned to Specific Job Form
class JobGarmsForm(forms.ModelForm):
    class Meta:
        model = Joboutfits
        fields = ["employeeid", "job", "garmenttype", 
                  "garmdescription", "garmsize", "multiuse", "totalperjob",
                  "reservestock", "garmentdefaultid", "jobid", ]

# Employee Stats Regarding Garms Assigned to Employye
class EmpGarmStatsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentorderstats
        fields = ["employeeid", "garmenttype", "empgarmpar", "totaljobpar", 
                  "totalreservestock", "maxorder", ]







###### Garment Orders Tab ########

#Order Landing Table
class SearchOrders(forms.ModelForm):
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Searchgarmorders
        fields = ["garmentorderid", "employeeid", "garmentdefaultid",  "garmenttype", "garmdescription",
                  "amount", "reason", "orderplaceddate", "orderplacedby", "orderstatus",  ]#"job",



# Garment Orders Search Form 
class GarmentOrdersForm(forms.ModelForm):
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'missing'}), initial=date.today)
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'placedon'}), initial=date.today)
    reason = forms.CharField(widget=TextInput(attrs={'class':'reason'}))
    orderstatus = forms.ChoiceField(choices=Garmentorders.statusChoices)
    loaned = forms.ChoiceField(choices=Garmentorders.loanedChoices)
    amount = forms.CharField(widget=forms.TextInput(attrs={'class':'amt'}))
    orderplacedby = forms.CharField(widget=forms.TextInput(attrs={'class':'placedby'}))

    class Meta:
        model = Garmentorders
        fields =  ["employeeid", "reason", "amount",
                  "orderplaceddate", "orderplacedby", "orderstatus", 
                  "missing", "loaned",]



class GarmentOrderIDStats(forms.ModelForm):
    class Meta:
        model = Garmorderidstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentorderid"]



    #ogarms = {}
    #list_garmdef= []
    #for garm in Garmdefaultvalues.objects.all():
    #    if garm.jobid.job in ogarms:
    #        ogarms[garm.jobid.job].append(garm.garmentdefaultdef)
    #    else:
    #        ogarms[garm.jobid.job] = [garm.garmentdefaultdef]
    #    list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    #jobchoices = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    #select_job = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobchoices]))
    #select_garmdef = forms.ChoiceField(choices=(list_garmdef))

    #jobchoices = json.dumps(jobchoices)
    #garmchoices = json.dumps(ogarms)

app/templates/app/inventory/AddGarment.html
{% extends "app/inventory/InventoryLayout.html" %}
{% block invcontent %}

{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static '../static/app/content/AddGarm.css' %}">
</head>

        <div id="addTitle">
            Add New Garment
        </div>
        
        <div class="blank"></div>
        
        <div class="InvForm">
            <form id="addGarm" class="AddGarmForm" method="POST">
                    {% csrf_token %}
                    {{ form }}
               <div class="SelectGarmentType">
                    <p id="selectGarmTypeInst">
                        Select Job The Garment Falls Under: 
                    </p>
                    <p class="SelectJob">
                        <label for="id_jobs_select">Select Job: </label>
                            <br>
                        {{ addgarm.jobs_select }}
                    </p>
                        <br>
                    <p class="SelectGarment">
                        <label for="id_garmdef_select">Select Garment Type: </label>
                            <br>
                        {{ addgarm.garmdef_select }}
                    </p>
                </div> 

                <div class="GarmentInfo">
                            
                    <p id="garmInfoInst">
                        Enter Garment Information Below
                    </p>

                    <div class="FirstRow">
                        <p id="garmnumber">
                            <label for="id_garmentnumber">Add Garment Number:</label>
                                <br>
                            {{ addgarm.garmentnumber }}
                        </p>
                        <p id="rfid">
                            <label for="id_rfid_barcode">RFID/Barcode #:</label>
                                <br>
                            {{ addgarm.rfid_barcode }}
                        </p>
                    </div>
                                
                    <div class="SecondRow">
                        <p id="slot">
                            <label for="id_slotnumber">Slot Number:</label>
                                <br>
                            {{ addgarm.slotnumber }}
                        </p>
                        <p id="conveyor">
                            <label for="id_conveyornumber">Conveyor #:</label>
                                <br>
                            {{ addgarm.conveyornumber }}
                        </p>
                        <p id="garmlocation">
                            <label for="id_garmlocation">Garm Location:</label>
                                <br>
                            {{ addgarm.garmlocation }}
                        </p>
                    </div>

                    <div class="ThirdRow">
                        <p id="missing">
                            <label for="id_missing">Missing: (Date)</label>
                            {{ addgarm.missing }}
                        </p>
                        <p id="loaned">
                            <label for="id_loaned">Loaned:</label>
                                <br>
                            {{ addgarm.loaned }}
                        </p>
                        <p id="altid">
                            <label for="id_altid">Alternate ID:</label>
                            {{ addgarm.altid }}
                        </p>
                    </div>
                </div>

                    <br>

                <div class="AssignEmployee">
                    <div id="employeeTitle">Assign Employee:</div>
                    <p id="enterEmp">
                        <label for="id_employeeid">Enter Employee ID: </label> <br>
                        {{ addgarm.emp_id }}
                    </p>                    
                    <p id="submit">
                        <input type="submit" id="saveGarm" value="Save Garment">
                    </p>  
                    <p id="fullname">
                        <label for="id_empfullname">Name: </label> <br>
                    </p>
                </div> 
                 
            </form>
        </div>

    {% endblock %}
    
    
    {% block actionbuttons %}
        <div class="Add" onclick="window.location.href='{%  url 'AddGarment' %}'">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add</button>
        </div>
    
    <script language="javascript">
        $('#id_jobs_select').change(function() {populateGarmDef(this)});
        
        jobs = {{ addgarm.jobs | safe }};
        garms = {{ addgarm.garms | safe }};

        populateJob();
        $("#id_garmdef_select").empty();
        $("#id_garmdef_select").append('<option value="" disabled selected>Select Job First</option>');
        function populateJob() {
            $('#id_jobs_select').empty();
            $("#id_jobs_select").append('<option value="" disabled selected>Select Job</option>');
            $.each(jobs, function(v) {
                $('#id_jobs_select')
                    .append($("<option></option>")
                    .attr("value", jobs[v])
                    .text(jobs[v]));
            });
        }

        function populateGarmDef(event) {
            job = $("#id_jobs_select option:selected").text();
            $("#id_garmdef_select").empty();
            $("#id_garmdef_select").append('<option value="" disabled selected>Select Garment Type</option>');
            for (let [b, bgarms] of Object.entries(garms)) {
                if (b == job) {                    
                    for (garm in bgarms) {
                        $('#id_garmdef_select')
                            .append($("<option></option>")
                                .attr("value", bgarms[garm])
                                .text(bgarms[garm]));
                    }
                }
            }
        }
    </script>

{% endblock %}

app/templates/app/inventory/InventoryLanding.html
{% extends "app/inventory/InventoryLayout.html" %}

{% block invcontent %}

{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static '../static/app/content/InventoryLanding.css' %}">
</head>


        <div class="Title">
            <h2>Search Inventory</h2>
        </div>

        <div class="blank"></div>

        <div class="InvSearchBox">

            <div class="ID_Search">
                <p>Garment Number</p>
                <input type="number" class="ID" id="IdInput" onkeyup="IDSearch()" onfocus="this.value=''">
            </div>

            <div class="FirstSec">
                <div class="JobID">
                    <p>Job</p>
                    <input type="number" class="Job" id="JobInput" onkeyup="JobSearch()" onfocus="this.value=''">
                </div>

                <div class="EmpID">
                    <p>Employee ID</p>
                    <input type="number" class="Emp" id="EmpInput" onkeyup="EmpSearch()" onfocus="this.value=''">
                </div>
            </div>

            <div class="SecondSec">
                <div class="RFID">
                    <p>RFID/Barcode</p>
                    <input type="number" class="Rfid" id="RFIDInput" onkeyup="RFIDSearch()" onfocus="this.value=''">
                </div>

                <div class="AltID">
                    <p>Alt ID</p>
                    <input type="number" class="Alt" id="AltInput" onkeyup="AltSearch()" onfocus="this.value=''">
                </div>
            </div>

            <div class="InvSearchButtons">
                <a href="{% url 'InventoryLanding' %}" class="InventorySearch" id="inventoryButton">
                    <p id="resetinv">Reset</p>
                </a>
            </div> 
        </div>

        <div class="InvTable">
            <div class="InvSearch">
                <table class="table table-bordered" id="invtable">
                    <thead>
                        <tr>
                            <th>Garment<br> Number &nbsp;&nbsp;&#8645;</th>
                            <th>RFID/<br> Barcode &nbsp;&nbsp;&#8645;</th>
                            <th>Job &nbsp;&nbsp;&#8645;</th>
                            <th>Type &nbsp;&nbsp;&#8645;</th>
                            <th>Emp ID &nbsp;&nbsp;&#8645;</th>
                            <th>Alt ID &nbsp;&nbsp;&#8645;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inv in invsearch %}
                            <tr>
                                <td><a href="/GarmentDetails/{{inv.garmentnumber}}">{{ inv.garmentnumber }}</a></td>
                                <td>{{ inv.rfid }}</td>
                                <td>{{ inv.job }}</td>
                                <td>{{ inv.description }}</td>
                                <td><a href="/EmployeeDetails/{{inv.employeeid}}">{{ inv.employeeid }}</a></td>
                                <td>{{ inv.altid }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    <script type="text/javascript" language="javascript" src="../static/app/scripts/InventoryLanding.js"></script>        

    {% endblock %}

app/templates/app/inventory/InventoryLayout.html
{% extends "app/layout.html" %}
{% block maincontent %}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static '../static/app/content/InventoryLayout.css' %}">
</head>

    <div class="ActionButtons">
        <div class="Add" onclick="window.location.href='{%  url 'AddGarment' %}'">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add<br>Garment</button>
        </div>
    </div>

    <div class="InventoryResults">

        {% block invcontent %}
        {% endblock %}

    </div>

{% endblock %}

app/templates/app/inventory/JS stuff.html
<tr>
	<td>
		<input id='id_ord-" + form_num + "-DELETE del' type='checkbox' name='ord-" + form_num + "-DELETE'>
	</td>
	<td><input id='id_ord-" + form_num + "-missing' type='date' name='ord-" + form_num + "-missing' class='missing'></td>

	<td><select id='id_ord-" + form_num + "-loaned' name='ord-" + form_num + "-loaned' class='loaned'></select></td>

	<td><input id='id_ord-" + form_num + "-reason' type='text' name='ord-" + form_num + "-reason'></td>

	<td><input id='id_ord-" + form_num + "-amount' type='number' name='ord-" + form_num + "-amount' class='amount'></td>

	<td><input id='id_ord-" + form_num + "-orderplaceddate' type='date' name='ord-" + form_num + "-orderplaceddate' class='orderdate'/></td>

	<td><input id='id_ord-" + form_num + "-orderplacedby' type='text' name='ord-" + form_num + "-orderplacedby' class='placedby'></td>

	<td><select id='id_ord-" + form_num + "-orderstatus' name='ord-" + form_num + "-orderstatus' class='status'></select></td>

</tr>



        var form_num = document.getElementById('id_ord-INITIAL_FORMS').getAttribute('value');

        $(document).ready(function() {
            $("#add_more").click(function() {
                form_num ++;
                $("input[id='id_ord-TOTAL_FORMS']").attr('value', form_num --);
                $("#ordersTable").prepend("<tr> <td><input id='id_ord-" + form_num + "-DELETE del' type='checkbox' name='ord-" + form_num + "-DELETE'></td> <td><input id='id_ord-" + form_num + "-missing' type='date' name='ord-" + form_num + "-missing'></td> <td><select id='id_ord-" + form_num + "-loaned' name='ord-" + form_num + "-loaned'></select></td> <td><input id='id_ord-" + form_num + "-reason' type='text' name='ord-" + form_num + "-reason'></td> <td><input id='id_ord-" + form_num + "-amount' type='number' name='ord-" + form_num + "-amount'></td> <td><input id='id_ord-" + form_num + "-orderplaceddate' type='date' name='ord-" + form_num + "-orderplaceddate'></td> <td><input id='id_ord-" + form_num + "-orderplacedby' type='text' name='ord-" + form_num + "-orderplacedby'></td> <td><select id='id_ord-" + form_num + "-orderstatus' name='ord-" + form_num + "-orderstatus' class='status'></select></td></tr>");
            });
        });













    #extra_forms = 0

    ## Inline Formset for user input into table + order table
    #NewOrderFormSet = inlineformset_factory(
    #    Garmdefaultvalues, Garmentorders, form=GarmentOrdersForm,
    #    fields=["missing", "loaned", "reason", "amount", "orderplaceddate", "orderplacedby", "orderstatus",],
    #    fk_name = 'garmentdefaultid',
    #    extra = extra_forms,
    #    can_delete = True,        
    #)



    #if request.method == 'POST' and 'order' in request.POST:
    #    formset = NewOrderFormSet(request.POST, instance=gdefid)
       
    #    if formset.is_valid():
    #        for i in range(0, formset.total_form_count()):
    #            form = formset.forms[i]
    #            form.save()
    #        formset.save()
    #        return HttpResponseRedirect("/GarmentDetails/"+garmentnumber_garmentdefaultid)
    #else:
    #    formset = NewOrderFormSet(instance=gdefid)