urls.py
"""
Definition of urls for WCI_GarmentInventory.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('app.urls'), name="home"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

app/forms.py
"""
Definition of forms.
"""
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import *
import json
from datetime import date
from django.forms.widgets import *
from django.utils.translation import ugettext_lazy as _

# Login Form
class BootstrapAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=200,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

# Customer Support Form
IssueOptions=[
    ('rehomed', 'Conveyor needs to be Rehomed'),
    ('power', 'Power outage'),
    ('slots', 'Slot numbers are off'),
    ('info', 'Employee or Garment information cannot be found'),
    ('sql', 'Database is not updating'),
    ('keypad', 'Keypad is not working'),
    ('other', 'If reason is not listed, please explain below')
]

class CustomerServiceForm(forms.Form):
    name = forms.CharField(max_length=40)
    email = forms.EmailField()
    to = forms.EmailField()
    issue = forms.ChoiceField(choices=IssueOptions)
    comments = forms.CharField(required=False, widget=forms.Textarea)



##### INVENTORY TAB INFORMATION ######

# Garment Info Form
class GarmSortForm(forms.ModelForm):  
    # Can search by JOB to filter specific Garments related to Job
    dgarms = {}
    list_garmdef= []
    for garm in Garmdefaultvalues.objects.all():
        if garm.jobid.job in dgarms:
            dgarms[garm.jobid.job].append(garm.garmentdefaultdef)
        else:
            dgarms[garm.jobid.job] = [garm.garmentdefaultdef]
        list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    jobs = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    jobs_select = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobs]))
    garmdef_select = forms.ChoiceField(choices=(list_garmdef))

    jobs = json.dumps(jobs)
    garms = json.dumps(dgarms)

    #EmployeeID filters specific Employee Name 

    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice, required=False)
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    slotnumber = forms.IntegerField(required=False)
    pickupdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local'}), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dropoffdate = forms.DateTimeField(widget=TextInput(attrs={'type': 'datetime-local', }), input_formats=['%m/%d/%y %H:%M'], initial=date.today, required=False)
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)


    class Meta:
        model = Garmentinvactivity
        fields = [ "jobs_select", "garmdef_select", "garmentnumber",
                 "slotnumber", "rfid_barcode", "conveyornumber", 
                 "garmlocation", "loaned", "missing", 
                 "altid", "employeeid", "jobid", "garmentdefaultid", "divdeptid",
                 "pickupdate", "dropoffdate", "dateadded", "alterations"]


# Inventory Search
class InvSearchForm(forms.ModelForm):
    class Meta:
        model = Inventorysearch
        fields = ["garmentnumber", "rfid", "job",
                  "description", "employeeid", "garmentdefaultid", ]
#"employeename",

# Inv Stats per Garment Number
class GarmInvStatsForm(forms.ModelForm):
    class Meta:
        model = Garminvstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentdefaultid", "jobid",
                    "job", "garmentnumber", ]

class GarmActForm(forms.ModelForm):
    dateadded = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)
    loaned = forms.ChoiceField(choices=Garmentinvactivity.loanedChoice)
    assigned = forms.ChoiceField(choices=Garmentinvactivity.assignedChoice)

    class Meta:
        model = Garmentinvactivity
        fields = '__all__'




###### EMPLOYEE TAB INFORMATION ######

# Employee Information Tab
class EmpInfoForm(forms.ModelForm):
    #djobs = {}
    #list_jobs = []
    #for jd in Jobdefinitions.objects.all():
    #    if jd.divdeptid.combineddef in djobs:
    #        djobs[jd.divdeptid.combineddef].append(jd.job)
    #    else:
    #        djobs[jd.divdeptid.combineddef] = [jd.job]
    #    list_jobs.append((jd.job, jd.job))

    #divs = [str(divdept_name) for divdept_name in Divdept.objects.all()]

    #divdept_select = forms.ChoiceField(choices=([(divdept_name, divdept_name) for divdept_name in divs]))
    #jobdef_select = forms.ChoiceField(choices=(list_jobs))
    
    #divs = json.dumps(divs)
    #jobs = json.dumps(djobs)

    gender = forms.ChoiceField(choices=Employeecreate.genderChoices, required=False)
    garmsize = forms.ChoiceField(choices=Employeecreate.garmSizeChoices, required=False)
    hiredate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Employeecreate
        fields = [ "employeeid", "empfirstname", "emplastname", 
                  "gender", "shirtsize", "pantsize", "shoesize", "garmlength", 
                  "hiredate", "alterationinstructions", "empmiddleinitial",
                  "empemail", "slotassignment", "conveyor", "jacketsize", "jobid", "divdeptid"]
#"divdept_select", "jobdef_select",
# Assigned Garments (To Specific Employee) Form 
class AssignedGarmsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentinventory
        fields = ["employeeid", "garmentid", "rfid", "garmenttype", 
                  "slotnumber", "lastpickedup", "lastdroppedoff", "missing",
                  "empgarmpar", "garmentdefaultid",]

# Garments Assigned to Specific Job Form
class JobGarmsForm(forms.ModelForm):
    class Meta:
        model = Joboutfits
        fields = ["employeeid", "job", "garmenttype", 
                  "garmdescription", "garmsize", "multiuse", "totalperjob",
                  "reservestock", "garmentdefaultid", "jobid", ]

# Employee Stats Regarding Garms Assigned to Employye
class EmpGarmStatsForm(forms.ModelForm):
    class Meta:
        model = Employeegarmentorderstats
        fields = ["employeeid", "garmenttype", "empgarmpar", "totaljobpar", 
                  "totalreservestock", "maxorder", ]







###### Garment Orders Tab ########

#Order Landing Table
class SearchOrders(forms.ModelForm):
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), initial=date.today, required=False)

    class Meta:
        model = Searchgarmorders
        fields = ["garmentorderid", "employeeid", "garmentdefaultid",  "garmenttype", "garmdescription",
                  "amount", "reason", "orderplaceddate", "orderplacedby", "orderstatus",  ]#"job",



# Garment Orders Search Form 
class GarmentOrdersForm(forms.ModelForm):
    missing = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'missing'}), initial=date.today)
    orderplaceddate = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'class': 'placedon'}), initial=date.today)
    reason = forms.CharField(widget=TextInput(attrs={'class':'reason'}))
    orderstatus = forms.ChoiceField(choices=Garmentorders.statusChoices)
    loaned = forms.ChoiceField(choices=Garmentorders.loanedChoices)
    amount = forms.CharField(widget=forms.TextInput(attrs={'class':'amt'}))
    orderplacedby = forms.CharField(widget=forms.TextInput(attrs={'class':'placedby'}))

    class Meta:
        model = Garmentorders
        fields =  ["employeeid", "reason", "amount",
                  "orderplaceddate", "orderplacedby", "orderstatus", 
                  "missing", "loaned",]



class GarmentOrderIDStats(forms.ModelForm):
    class Meta:
        model = Garmorderidstats
        fields = ["garmenttype", "totalperjob", "totalreservestock",
                    "maxamountinv", "totalinv", "totalassigned", 
                    "totalunassigned", "percentfull", "garmentorderid"]



    #ogarms = {}
    #list_garmdef= []
    #for garm in Garmdefaultvalues.objects.all():
    #    if garm.jobid.job in ogarms:
    #        ogarms[garm.jobid.job].append(garm.garmentdefaultdef)
    #    else:
    #        ogarms[garm.jobid.job] = [garm.garmentdefaultdef]
    #    list_garmdef.append((garm.garmentdefaultdef, garm.garmentdefaultdef))

    #jobchoices = [str(job_name) for job_name in Jobdefinitions.objects.all()]

    #select_job = forms.ChoiceField(choices=([(job_name, job_name) for job_name in jobchoices]))
    #select_garmdef = forms.ChoiceField(choices=(list_garmdef))

    #jobchoices = json.dumps(jobchoices)
    #garmchoices = json.dumps(ogarms)

app/templates/app/employee/EmployeeCreate.html
{% extends "app/employee/EmployeeLayout.html" %}

{% block empcontent %}

<head>
    <link rel="stylesheet" type="text/css" href="../static/app/content/EmployeeCreate.css">
</head>

        <div class="EmpTabs">
            <button id="Info" class="TabSelect tablink active" onclick="openTab(event, 'employeeInfo')">New Employee</button>

        </div>

        <div class="blank"></div>

        <div class="EmpForm">
            <form class="EmployeeInfo" id="employeeInfo" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="Employee">
                    <div class="FirstRow">
                        <p id="employeeid">
                            <label for="id_employeeid">Employee ID</label>
                                <br>
                            {{ addempform.employeeid }}
                        </p>
                    </div>

                    <div class="SecondRow">
                        <p id="firstName">
                            <label for="id_empfirstname">First Name</label>
                                <br>
                            {{ addempform.empfirstname }}
                        </p>
                        <p id="lastName">
                            <label for="id_emplastname">Last Name</label>
                                <br>
                            {{ addempform.emplastname }}
                        </p>
                    </div>
                
                    <div class="ThirdRow">
                        <p id="dept">
                            <label for="id_combineddef">Select Div/Dept: </label>
                                <br>
                            {{ addempform.combineddef }}
                        </p>                        
                        <p id="job">
                            <label for="id_jobid">Select Job: </label>
                                <br>
                            <input id="id_jobid" value="{{ addempform.jobid }}">
                        </p>
                    </div>

                    <div class="FourthRow">
                        <p id="hire">
                            <label for="id_hiredate">Hire Date</label>
                                <br>
                            {{ addempform.hiredate }}
                        </p>
                    </div>
                
                </div>

                <div class="Garment">
                    <div class="FirstRow">
                        <p id="slot">
                            <label for="slotassignment">Assigned Slot#</label>
                                <br>
                            {{addempform.slotassignment}}
                        </p>
                        <p id="conveyor">
                            <label for="id_conveyor">Conveyor #</label>
                                <br>
                            {{addempform.conveyor}}
                        </p> 
                    </div>

                    <div class="SecondRow">
                        <p id="gender">
                            <label for="id_gender">Gender</label>
                                <br>
                            {{addempform.gender}}
                        </p>  
                        <p id="email">
                            <label for="id_gender">Email</label>
                                <br>
                            {{addempform.empemail}}
                        </p>  
                    </div>

                    <div class="ThirdRow">
                        <p id="shirtSize">
                            <label for="id_shirtsize">Shirt Size:</label>
                                <br>
                            {{addempform.shirtsize}}
                        </p>                         
                        <p id="pantSize">
                            <label for="id_pantsize">Pant Size</label>
                                <br>
                            {{addempform.pantsize}}
                        </p>   
                    </div>

                    <div class="FifthRow">
                        <p id="altInst">
                            <label for="id_alterationinstructions">Alterations</label>
                                <br>
                            {{addempform.alterationinstructions}}
                        </p>
                    </div>

                    <div class="FourthRow">
                        <p id="shoeSize">
                            <label for="id_shoesize">Shoe Size</label>
                                <br>
                            {{addempform.shoesize}}
                        </p>                         
                        <p id="jacketSize">
                            <label for="id_jacketsize">Jacket Size</label>
                                <br>
                            {{addempform.jacketsize}}
                        </p>
                    </div>

                </div>

                <div class="Submit">
                     <input type="submit" id="saveEmp" value="Save Employee">
                </div>

            </form>
        </div>


    {% endblock %}
        
    {% block actionbuttons %}
        <a href="{% url 'EmployeeCreate' %}" class="Add">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add</button>
        </a>

    <script language="Javascript" type="text/javascript" src="../static/app/scripts/EmpDetails.js"></script>

    <script language="javascript">
        $( function() {
            var availableTags = [
                {% for dept in divdepts %}
                    "{{dept.combineddef}}",
                {% endfor %}
            ];
            $( "#id_combineddef" ).autocomplete({
              source: availableTags
            });
          } );
        $( function() {

            var availableTags = [
                {% for job in divdepts %}
                    "{{job.jobid}}",
                {% endfor %}
            ];
            $( "#id_jobid" ).autocomplete({
              source: availableTags
            });
          } );
    </script>

    {% endblock %}

app/templates/app/employee/EmployeeLanding.html
{% extends "app/employee/EmployeeLayout.html" %}

{% block empcontent %}
<head>
    <link rel="stylesheet" type="text/css" href="../static/app/content/EmployeeLanding.css">
    <script type="text/javascript" src= "../static/app/scripts/jquery-1.3.2.js"></script>
    <script type="text/javascript" src= "../static/app/scripts/jquery-ui.js"></script> 
</head>

        <div class="Title">
                <h2>Search Employee </h2>
        </div>

        <div class="blank"></div>

            <div class="EmpSearchBox">
                
                <div class="ID_Search"ID>
                    <p>Employee ID</p>
                    <input type="number" class="ID" id="IdInput" onkeyup="IDSearch()" onfocus="this.value=''">
                </div> 
                
                <div class="FirstSec">
                    <div class="First_Search">
                        <p>First Name</p>
                        <input type="text" class="First" id="FirstNameInput" onkeyup="FirstSearch()" onfocus="this.value=''">
                    </div> 

                    <div class="Last_Search">
                        <p>Last Name</p>
                        <input type="text" class="Last" id="LastNameInput" onkeyup="LastSearch()" onfocus="this.value=''">
                    </div>
                </div>

                <div class="SecondSec">
                    <div class="Dept_Search">
                        <p>Department</p>
                        <input type="text" class="Dept" id="DeptInput" onkeyup="DeptSearch()" onfocus="this.value=''">
                    </div>

                    <div class="Job_Search">
                        <p>Job</p>
                        <input type="text" class="Job" id="JobInput" onkeyup="JobSearch()" onfocus="this.value=''">
                    </div>
                </div>

                <div class="EmpSearchButtons">  
                    <a href="{% url 'EmployeeLanding' %}" class="EmployeeSearch" id="inventoryButton">
                        <p id="resetemp">Reset</p>
                    </a>
                </div> 
            </div>

            <div class="EmpTable">
                <div class="EmpSearch">
                    <table class="table table-bordered" id="emptable">
                        <thead>
                                <th>
                                    Employee ID &nbsp;&nbsp;&#8645;
                                </th>
                                <th>
                                    First Name &nbsp;&nbsp;&#8645;
                                </th>
                                <th>
                                    Last Name &nbsp;&nbsp;&#8645;
                                </th>
                                <th>
                                    Department &nbsp;&nbsp;&#8645;
                                </th>
                                <th>
                                    Job &nbsp;&nbsp;&#8645;
                                </th>
                        </thead>
                        <tbody>
                            {% for row in empsearch %}
                                <tr>  
                                    <td>
                                        <a href="/EmployeeDetails/{{row.employeeid}}">{{row.employeeid}}
                                        </a>
                                    </td>
                                    <td>{{ row.firstname }}</td>
                                    <td>{{ row.lastname }}</td>
                                    <td>{{ row.department }}</td>
                                    <td>{{ row.job }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

    <script language="Javascript" type="text/javascript" src="../static/app/scripts/EmployeeLanding.js"></script>

    {% endblock %}
    

app/templates/app/employee/EmployeeLayout.html
{% extends "app/layout.html" %}
{% block maincontent %}
<head>
    <link rel="stylesheet" type="text/css" href="../static/app/content/EmployeeLayout.css">
</head>
    
    <div class="ActionButtons">
        <a href="{% url 'EmployeeCreate' %}" class="Add">
            <button class="AddButton" id="addButton" onclick="SelectAction()">Add<br>Employee</button>
        </a>
    </div>

    <div class="EmployeeResults">

        {% block empcontent %}
        {% endblock %}

    </div>
    


{% endblock %}